"""Create enrollments table

Revision ID: b44a5fc9988f
Revises: d15d1a2afc72
Create Date: 2024-10-12 13:22:54.952316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b44a5fc9988f"
down_revision: Union[str, None] = "d15d1a2afc72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrollments",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint(
            "participant_id", "event_id", name="unique_participant_event"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enrollments")
    # ### end Alembic commands ###
